apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: spring-petclinic-wfbn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: spring-petclinic-wfbn
    app.kubernetes.io/part-of: my-app-petclinic
  name: spring-petclinic-wfbn
  namespace: eyuen-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: spring-petclinic-wfbn
status:
  loadBalancer: {}
